"""A general grammar representation."""

from typing import Set, AbstractSet, Iterable, Optional, Hashable, TypeVar, Type
from abc import abstractmethod

from ..objects.cfg_objects import Variable, Terminal, Production
from ..objects.cfg_objects.utils import to_variable

GrammarT = TypeVar("GrammarT", bound="FormalGrammar")


class FormalGrammar:
    """A general grammar representation.

    Attributes
    ----------
    _variables:
        A finite set of variables of the grammar.
    _terminals:
        A finite set of terminals of the grammar.
    _start_symbol:
        The start symbol of the grammar, element of `_variables`.
    _productions:
        A finite set of productions or rules of the grammar.
    """

    @abstractmethod
    def __init__(self,
                 variables: AbstractSet[Hashable] = None,
                 terminals: AbstractSet[Hashable] = None,
                 start_symbol: Hashable = None,
                 productions: Iterable[Production] = None) -> None:
        """Initializes the grammar."""
        self._variables: Set[Variable]
        self._terminals: Set[Terminal]
        self._start_symbol: Optional[Variable]
        self._productions: Set[Production]

    @property
    def variables(self) -> Set[Variable]:
        """Gets the variables of the grammar."""
        return self._variables

    @property
    def terminals(self) -> Set[Terminal]:
        """Gets the terminals of the grammar."""
        return self._terminals

    @property
    def productions(self) -> Set[Production]:
        """Gets the productions of the grammar."""
        return self._productions

    @property
    def start_symbol(self) -> Optional[Variable]:
        """Gets the start symbol of the grammar."""
        return self._start_symbol

    def add_production(self, production: Production) -> None:
        """Adds the given production to the grammar.

        Parameters
        ----------
        production:
            The production to add.
        """
        self.variables.update(production.variables)
        self.terminals.update(production.terminals)
        self.productions.add(production)

    def add_start_symbol(self, symbol: Hashable) -> None:
        """Adds the start symbol to the grammar.

        Parameters
        ----------
        symbol:
            The start symbol to set for the grammar.
        """
        symbol = to_variable(symbol)
        self.variables.add(symbol)
        self._start_symbol = symbol

    def remove_start_symbol(self) -> None:
        """Removes the start symbol from the grammar."""
        self._start_symbol = None

    @abstractmethod
    def copy(self: GrammarT) -> GrammarT:
        """Copies the grammar.

        Returns
        -------
        A copy of current grammar.
        """
        raise NotImplementedError

    def __copy__(self: GrammarT) -> GrammarT:
        """Copies the grammar."""
        return self.copy()

    @classmethod
    def _copy_from(cls: Type[GrammarT], other: GrammarT) -> GrammarT:
        return cls(variables=other.variables,
                   terminals=other.terminals,
                   productions=other.productions,
                   start_symbol=other.start_symbol)

    @abstractmethod
    def generate_epsilon(self) -> bool:
        """Checks if the grammar generates epsilon.

        Returns
        -------
        Whether epsilon is generated by the grammar.
        """
        raise NotImplementedError

    @abstractmethod
    def to_normal_form(self) -> "FormalGrammar":
        """Gets the Chomsky Normal Form of current grammar.

        Returns
        -------
        An equivalent grammar in the CNF.
        """
        raise NotImplementedError

    def is_normal_form(self) -> bool:
        """Checks if the current grammar is in Chomsky Normal Form.

        Returns
        -------
        Whether the current grammar is in CNF.
        """
        return all(
            production.is_normal_form() for production in self._productions)

    def to_text(self) -> str:
        """Turns the grammar into its string representation.

        This might lose some type information and the start_symbol.

        Returns
        -------
        The grammar as a string.
        """
        res = []
        for production in self._productions:
            res.append(str(production.head) + " -> " +
                       " ".join([x.to_text() for x in production.body]))
        return "\n".join(res) + "\n"

    @classmethod
    def from_text(
        cls: Type[GrammarT],
        text: str,
        start_symbol: Optional[Hashable] = Variable("S")) \
            -> GrammarT:
        """Read a grammar from the given text.

        The text contains one rule per line.
        The structure of a production is:
        head -> body1 | body2 | ... | bodyn
        where | separates the bodies.
        A variable (or non terminal) begins by a capital letter.
        A terminal begins by a non-capital character
        Terminals and Variables are separated by spaces.
        An epsilon symbol can be represented by epsilon, $, ε, ϵ or Є.
        If you want to have a variable name starting with a non-capital \
        letter or a terminal starting with a capital letter, you can \
        explicitly give the type of your symbol with "VAR:yourVariableName" \
        or "TER:yourTerminalName" (with the quotation marks). For example:
        S -> "TER:John" "VAR:d" a b

        Parameters
        ----------
        text:
            The text of transform.
        start_symbol:
            The start symbol of the new grammar.

        Returns
        -------
        A grammar obtained from the given text.
        """
        variables = set()
        productions = set()
        terminals = set()
        cls._read_text(text, productions, terminals, variables)
        return cls(variables=variables,
                   terminals=terminals,
                   productions=productions,
                   start_symbol=start_symbol)

    @classmethod
    def _read_text(cls,
                   text: str,
                   productions: Set[Production],
                   terminals: Set[Terminal],
                   variables: Set[Variable]) -> None:
        """Reads the given text and updates the given grammar properties.

        Parameters
        ----------
        text:
            The text to read.
        productions:
            Grammar productions to update from the text.
        terminals:
            Grammar terminals to update from the text.
        variables:
            Grammar variables to update from the text.
        """
        for line in text.splitlines():
            line = line.strip()
            if not line:
                continue
            cls._read_line(line, productions, terminals, variables)

    @classmethod
    @abstractmethod
    def _read_line(cls,
                   line: str,
                   productions: Set[Production],
                   terminals: Set[Terminal],
                   variables: Set[Variable]) -> None:
        """Reads the given line and updates the given grammar properties.

        Parameters
        ----------
        line:
            The line to read.
        productions:
            Grammar productions to update from the given line.
        terminals:
            Grammar terminals to update from the given line.
        variables:
            Grammar variables to update from the given line.
        """
        raise NotImplementedError
